import Link from 'next/link';



export const metadata = {
  title: 'Belajar Next JS',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
  }) {
  
 
  
  return (
    <html lang="en">
      <head>
        <body>
          <ul>
            <li>
              <Link href="/">Home</Link>
            </li>
            <li>
              <Link href="/dashboard">Dashboard</Link>
            </li>
            <li>
              <Link href="/settings">Settings</Link>
            </li>
           
            
          </ul>
          {children}
        </body>
      </head>
    </html>
  )
}
